language: general

services:
  - docker

before_install:
  - docker pull acidgenomics/bioc-release
  - docker images

script:
  - docker run -ti --user bioc -v $PWD:/goalie acidgenomics/bioc-release Rscript -e 'source("/goalie/travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
