script: true

language: r
cache: packages
sudo: false
bioc_required: true

matrix:
  include:
  - os: linux
    r: bioc-release
    warnings_are_errors: true
  - os: linux
    r: bioc-devel
    latex: false
    warnings_are_errors: false
  - os: osx
    r: bioc-release
    fortran: false
    latex: false
    warnings_are_errors: false
  fast_finish: true

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - jimhester/lintr
  - steinbaugh/basejump.classes
  - steinbaugh/basejump.data
  - steinbaugh/basejump.experiment

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
