language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x travis-docker.sh

jobs:
  include:
    - stage: test
      name: "docker: bioc-3.9"
      script: tag="bioc-3.9" ./travis-docker.sh
    - stage: test
      name: "docker: bioc-3.8"
      script: tag="bioc-3.8" ./travis-docker.sh
    - stage: test
      name: "docker: bioc-3.6"
      script: tag="bioc-3.6" ./travis-docker.sh

after_failure:
  - env | sort
  - df -h
  - docker images

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
